name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.7'

            - name: Install apt packages
              run: |
                  sudo apt-get install libeigen3-dev libtinyxml-dev
            - name: Install latest scikit robot from source
              run: |
                  git clone https://github.com/iory/scikit-robot
                  cd scikit-robot
                  pip install . 
